[package]
name = "actix-learning"
version = "0.1.0"
edition = "2021"


[dependencies]
actix = "0.13.0"
actix-web = "4"
actix-web-actors = "4"
tokio = { version = "1", features = ["full"] }
log = "0.4.14"
futures = "0.3.21"
async-stream = "0.3.2"

diesel = { version = "1.4.8", features = ["r2d2", "sqlite"] }