[package]
name = "central-api"
version = "0.1.0"
edition = "2021"

[dependencies]
ws-com-framework = { git="https://github.com/file-share-platform/ws-com-framework" }
sha2 = "0.10.2"

async-trait = "0.1.53"

actix = "0.13.0"
actix-web = { version = "4", features = ["openssl"] }
actix-web-actors = "4"
openssl = { version = "0.10", features = ["v110"] }
tokio = { version = "1", features = ["full"] }
log = "0.4.14"
futures = "0.3.21"
async-stream = "0.3.2"

pretty_env_logger = "0.4.0"

rand = "0.8.5"
diesel = { version = "1.4.8", features = ["r2d2", "sqlite"] }

[dev-dependencies]
serde = {version = "1.0.136", features = ["derive"]}
serde_json = "1.0.59"