[package]
name = "central-api"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ws-com-framework= { git="https://github.com/file-share-platform/ws-com-framework", default-features = false, features = ["server", "wrapper-warp"], rev="3a9c2fa" }
tokio = { version = "1", default-features = false, features = ["sync", "macros"] }
warp = { version = "0.3", features = ["tls"] }
futures="0.3.16"
tokio-stream="0.1.7"
bytes="1"
mobc="0.7.3"
mobc-postgres = { version = "*", features = ["with-chrono-0_4"] }
chrono = { version = "0.4" }

bincode = "1.2.1"

#Cryptographic Crates
rand = { version = "0.8.4", default-features = false, features = ["std_rng"] }
sha2 = { version = "0.9.8" }